// game_config.h — Auto-generated by 3DS Studio. Do not edit manually.
#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

static constexpr float GC_MOVE_SPEED   = 3.50f;
static constexpr float GC_SPRINT_SPEED = 5.50f;
static constexpr float GC_JUMP_FORCE   = -7.80f;
static constexpr float GC_DJUMP_FORCE  = -9.00f;
static constexpr float GC_GRAVITY      = 0.48f;
static constexpr float GC_GRAVITY_FALL = 0.78f;
static constexpr float GC_DASH_SPEED   = 12.00f;

static constexpr bool DOUBLE_JUMP_ENABLED   = true;
static constexpr bool DIALOGUE_ENABLED      = true;
static constexpr bool WALL_JUMP_ENABLED = true;
static constexpr bool DASH_ENABLED = true;
static constexpr bool GROUND_POUND_ENABLED = true;

#endif // GAME_CONFIG_H
